create table if not exists telegram_bot_details (
    id bigint generated by default as identity primary key not null,
    chat_id integer not null,
    last_bot_message_id integer not null,
    created_at TIMESTAMPTZ not null default NOW(),
    updated_at TIMESTAMPTZ not null default NOW(),

    constraint unique_chat_id unique(chat_id)
);