create table if not exists interview_messages (
     id bigint generated by default as identity primary key not null,
     interview_id UUID not null,
     content text not null,
     role text not null,
     created_at TIMESTAMPTZ not null default NOW(),
     updated_at TIMESTAMPTZ not null default NOW(),

     foreign key (interview_id) references "interview" (id)
)