create table if not exists question (
    id UUID primary key not null,
    text text not null,
    job_position text default null,
    job_level text default null
);

create table if not exists interview_question (
    id bigint generated by default as identity primary key not null,
    interview_id UUID not null,
    question_id UUID not null,
    status text not null,

    foreign key (interview_id) references interview (id),
    foreign key (question_id) references question (id),
    constraint unique_interview_id_question_id unique(interview_id, question_id)
)