name: 'DB migrations based on golang/migrate'
description: 'DB migrations based on golang/migrate'
inputs:
  db-connection:
    description: 'db connection string'
    required: true
    default: ""
  source:
    description: 'source migrations'
    required: true
    default: ""
outputs:
  log:
    description: 'migration log'
runs:
  using: 'docker'
  image: 'docker://migrate/migrate'
  args:
    - '-source'
    - ${{ inputs.source }}
    - '-database'
    - postgres://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}
    - 'up'