name: migrations

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branch: [ 'main' ]


env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    runs-on: golang-migrate/migrate:latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Migrations
        run:  migrate -source "./db/migrations" -database "${{ env.DB_CONNECTION }}" up >> $GITHUB_OUTPUT
        shell: bash